---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(p8105.datasets)
library(tidyverse)
library(plotly)
data("instacart")
```

Column {data-width=450}
-----------------------------------------------------------------------

### Chart A

```{r}
reorder_highest = 
  instacart |> 
  filter(reordered==1) |> 
  group_by(department) |> 
  tally() |> 
  arrange(desc(n)) |> 
  head(40)

reorder_highest |> 
  plot_ly(x = ~department, 
        y = ~n, 
        type = 'bar') |> 
  layout(title = "Most repurchased items",
         xaxis = list(title = "Department", automargin = TRUE),
         yaxis = list(title = "Times of reordered",
                      tickformat = ",g"))


```

Column {data-width=550}
-----------------------------------------------------------------------

### Chart B

```{r}
order_time =
  instacart |> 
  group_by(order_hour_of_day) |> 
  distinct(order_id) |> 
  summarize(times = n()) |>
  rename(time = order_hour_of_day,
         frequency = times) 

order_time$time = as.factor(order_time$time)


order_time |> 
  plot_ly(x=~ time,
          y=~ frequency,
          type = "scatter",
          mode = "line") |> 
  layout(title = "The line plots of the time people would like to order" ,
         xaxis = list(title = "Time in a day"),
         yaxis = list(title = "Frequency"))
```

### Chart C

```{r}
department_numbers =
  instacart |> 
  group_by(department) |> 
  summarise(count = n())

department_numbers |> 
  plot_ly(labels = ~department,
        values = ~count,
        type = 'pie',
        textinfo = 'label+percent') |> 
  layout(title = "People's consumption preference")
```

